# Don't change this number unless you want to reset the config file!
Version: '0.1.1'

Updater:
  # Should this plugin be automatically updated
  Auto: true
  # Should you get a notification in the console if there is an update available, this wont happen if Auto is set to true
  Notify: false

# Change every AttractionStatus Settings
AttractionStatus:
  # Set the plugin prefix
  Prefix: "&6[AS]"
  # Set the language of the plugin
  Lang: "en_US"

# Change menu settings
Menus:
  # Attraction menu
  Attractions:
    # Default is from lang files menu.attractions.title
    # Title: "Attractions"
    Size: 54

  # Zones menu
  Zones:
    # Default is from lang files menu.zones.title
    # Title: "Zones"
    Size: 27